### ISSUE TITLE
Ansible playbook not working

### ISSUE THREAD

**Issue by badraoul** [vallard/CiscoCloudDayLab1#2]
trying to run Ansible exercise.  Your instructions very specifically call for Image ID, not image Name.    I edited the file copc-one.yml to add my image ID and key name.  See image below
![image](https://cloud.githubusercontent.com/assets/10123405/10088693/701d8b30-62d1-11e5-864c-661609f1e892.png)

Got an error, so I double-checked the image ID in Horizon.  It is confirmed.  See pic below.
![image](https://cloud.githubusercontent.com/assets/10123405/10088714/9bbcbc0c-62d1-11e5-98ae-631fa8ddfe99.png)

Still I get an error that says the image name is invalid.  See below:

$ ansible-playbook copc-one.yml

PLAY [launch one openstack instance] *****************************************\* 

TASK: [Ensure New server is up.] *********************************************\* 
failed: [localhost] => {"failed": true}
msg: unsupported parameter for module: image_name

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/user10/copc-one.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1   

$ 
$

**Comment by vallard** [comment]
There's two options you can use for specifying an image: 
`image_name` or `image_id` 

Looks like you're putting the ID of the image in the image name.  
http://docs.ansible.com/ansible/nova_compute_module.html

I think the lab only has Ansible 1.5 so image_name probably won't work, so you'll need to specify 

```
image_id: e63...
```

**Comment by vallard** [comment]
Also, its a bummer that we have to use Ansible 1.x for the lab as the nova_compute modules are no longer being supported but since Ansible 2.0 sucks for metapod right now that's all we can do. (see: https://groups.google.com/forum/#!topic/ansible-project/FwZthkNjlWA)

The good news is that the Ansible guys are on Metapod right now working on the issues.  Looking forward to updating the lab to use Ansible 2.0.

**Comment by badraoul** [comment]
OK.  I changed the "image_name" parameter to "image_id" and it appears to have worked.  You should update the instructions on the lab.

**Comment by badraoul** [comment]
Finished part one.  Took me most of the afternoon, but I was often distracted.  I think a relative beginner like me could get the Part One finished in 2 hours.  That includes simple troubleshooting.

Steve Watkins
stevwatk@cisco.com
408.910.1994

---

Jabber Guest Call Mehttps://reachme.cisco.com/call/stevwatk@cisco.com?name=Steve%20Watkins    Browser-based video chat.
