### ISSUE TITLE
New git users would get error when doing git commit for the first time

### ISSUE THREAD

**Issue by kamlesh333** [vallard/CiscoCloudDayLab1#4]
Reference -->  02-GitAndRegisteries/README.md

You may get an error if you are working with git for the first time, something like:
++
user09@f3f2e1b5cd02:~/Metacloud-test$ git commit -am "kshah changes"

**\* Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
++

Go ahead and run the "git config" commands as per above if you get this message. Now return back to doing git commit as per above

**Comment by vallard** [comment]
Nice, yes, this will be added to docs.

**Comment by fasihsajid** [comment]
still getting the same error

**Comment by vallard** [comment]
Are you logged in as a Git user somewhere?

**Comment by honoremwise** [comment]
yes

**Comment by honoremwise** [comment]
but still failed to commit  someone to help please

**Comment by B1ueMang0** [comment]
As a new git user I received the same message. Using `git config --list` will print out your current config information. If you find that either your name or email is present, but not both, then that could be why it still isn't working. 

You will need to ensure you have run both git config (user.name and user.email) instructions as above and then you can try git commit again. 

Hope it works.

**Comment by almazoon** [comment]
same error

**Comment by almazoon** [comment]
is any  solution

**Comment by vallard** [comment]
@almazoon if you are getting the  error then it git doesn't think you are logged in.  Can you cut and paste the exact error?

**Comment by pradeep2123** [comment]
re.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true








 same error in  past comment, i recieved. What is the remedies for that. pls, give exact solution

    help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.heroku.url=https://git.heroku.com/pradeepoauth.git
remote.heroku.fetch=+refs/heads/*:refs/remotes/heroku/*

**Comment by pradeep2123** [comment]
i can't able to commit.

**Comment by ghost** [comment]
Thanks, this was very helpful.

**Comment by Ebony766** [comment]
$ git commit -m "added code to HTML file"
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
